version: 0.2

# CodeBuild buildspec for deploying the Astro site to S3 + CloudFront.
# Required environment variables (configure in CodeBuild project):
# - BUCKET: S3 bucket name for hosting (e.g., subaru-is-running-site)
# - DISTRIBUTION_ID: CloudFront distribution ID (e.g., E123ABC456DEF)
# Optional environment variables:
# - APP_DIR: path to app within the repo (default: astro-blog)

env:
  variables:
    APP_DIR: "astro-blog"

phases:
  install:
    commands:
      - echo Node: $(node -v); NPM: $(npm -v)
      - echo Installing dependencies in $APP_DIR with dev deps
      - export NODE_ENV=development
      - npm ci --prefix $APP_DIR
  build:
    commands:
      - echo Building in $APP_DIR
      - npm run build --prefix $APP_DIR
  post_build:
    commands:
      - |
        if [ -d "$APP_DIR/dist" ]; then
          echo Syncing $APP_DIR/dist to s3://$BUCKET
          aws s3 sync $APP_DIR/dist s3://$BUCKET --delete
          echo Invalidating CloudFront distribution $DISTRIBUTION_ID
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
        else
          echo "No build output found at $APP_DIR/dist. Skipping deploy."
        fi

# Optional: also publish the built site as a pipeline artifact.
artifacts:
  base-directory: astro-blog/dist
  files:
    - '**/*'
