version: 0.2

env:
  variables:
    ASTRO_TELEMETRY_DISABLED: "1"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm --prefix ../admin-app ci
      - npm ci
  pre_build:
    commands:
      - echo Generating monthly summaries...
      - npm run gen:summary
  build:
    commands:
      - echo Building Astro site...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: dist

cache:
  paths:
    - '../admin-app/node_modules/**/*'
    - 'node_modules/**/*'

